site_name: García Hermanos Agroindustrial S.R.L.
site_url: https://garciahnos.github.io/Onbording/

nav:
  - Inicio: index.md
  - Estrategia: estrategia/estrategia.md
  - Event Storming: estrategia/eventStorming.md
  - Git, GitHub & GitFlow: 
    - Introduccion: git/introduccionGit/introduccionGit.md
    - Configuracion Inicial: git/configInicial/configInicial.md
    - Directorios: git/directorios/directorios.md
    - Manejo de Repositorios: git/manejoDeRepositorios/manejoDeRepositorios.md
    - Git Flow: git/gitFlow/gitFlow.md
  - Draft: 
    - Relevamiento de Programas: draft/relevamientoProgramas/relevamientoProgramas.md
  - MkDocs: mkDocs/mkDocs.md
  

site_author: It
site_description: >-
  Onbording

repo_name: Onbording
repo_url: https://github.com/GarciaHnos/Onbording

theme:
  name: material 
  language: es
  logo: assets/logo-gh.png 
  favicon: assets/logo-gh.png 
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - admonition 