site_name: García Hermanos Agroindustrial S.R.L.
site_url: https://garciahnos.github.io/Onbording/

nav:
  - <b>Inicio</b>: index.md
  - <b>Enfoque Metodológico</b>:
      - <b>Git</b>: 
          - "<span class='material-icons'>menu_book</span> Introducción": enfoque-metodologico/git/introduccionGit/introduccionGit.md
          - "<span class='material-icons'>settings</span> Configuración Inicial": enfoque-metodologico/git/configInicial/configInicial.md
          - "<span class='material-icons'>folder</span> Directorios": enfoque-metodologico/git/directorios/directorios.md
          - "<span class='material-icons'>storage</span> Manejo de Repositorios": enfoque-metodologico/git/manejoDeRepositorios/manejoDeRepositorios.md
          - "<span class='material-icons'>track_changes</span> Git Flow": enfoque-metodologico/git/gitFlow/gitFlow.md
      - <b> Nomenclatura Cammel</b>:
          - "<span class='material-icons'>code</span> Nomenclatura Cammel": enfoque-metodologico/nomeclatura/nomenclatura.md
      - <b>Principios SOLID</b>:
          - "<span class='material-icons'>lightbulb</span> Principios SOLID": enfoque-metodologico/principiosSOLID/principios_solid.md
      - <b>Clean Code</b>:
          - "<span class='material-icons'>clean_hands</span> Clean Code": enfoque-metodologico/clean-code/cleancode.md
      - <b>Clean Architecture</b>: 
          - "<span class='material-icons'>architecture</span> Clean Architecture": enfoque-metodologico/clean-architecture/cleanarchitecture.md
  - <b>Proyectos</b>: 
      - "<b><span class='material-icons'>search</span> Relevamiento de Programas</b>": proyectos/relevamientoProgramas/relevamientoProgramas.md
  - <b>Contribución</b>:
      - "<span class='material-icons'>rocket</span> Introducción": contribucion/introduccion/introduccion.md
      - <b>MkDocs</b>:
          - "<span class='material-icons'>group</span> Contribución": contribucion/mkDocs/Contribucion/contribucion.md
          - "<span class='material-icons'>explore</span> Navegación": contribucion/mkDocs/Navegacion/navegacion.md
          - "<span class='material-icons'>visibility</span> Previsualización": contribucion/mkDocs/Previsualización/previsualizacion.md
          - "<span class='material-icons'>cloud_upload</span> Despliegue": contribucion/mkDocs/Despliegue/despliegue.md
      - <b>Markdown</b>:
          - "<span class='material-icons'>code</span> Introducción": contribucion/MarkDown/Introduccion/Introduccion.md
          - "<span class='material-icons'>code</span> Sintaxis Básica": contribucion/MarkDown/Sintaxis_Basica/sintaxis_basica.md
          - "<span class='material-icons'>code</span> Sintaxis Avanzada": contribucion/MarkDown/Sintaxis_Avanzada/Sintaxis_avanzada.md
  - <b>DevOps</b>:    
      - <b> Proyectos</b>:
          - "<b><span class='material-icons'>rocket</span> Onbording</b>": 
              - "<span class='material-icons'>cloud_upload</span> Despliegue": devops/onbording/expli-despliegue.md

site_author: It
site_description: >-
  Onbording

repo_name: Onbording
repo_url: https://github.com/GarciaHnos/Onbording

theme:
  name: material 
  language: es
  toc: false
  icon:
    repo: fontawesome/brands/github
    search: fontawesome/solid/search
  custom_dir: material/overrides
  logo: assets/logo-gh-blanco.png
  favicon: assets/logo-gh.png 
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night   # ícono modo oscuro
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny  # ícono modo claro
        name: Cambiar a modo claro
  features:
    - navigation.top           # Navbar arriba
    - navigation.tabs          # Opcional: menús como pestañas
    - navigation.tracking      # Resalta en qué sección estás
    - search.highlight         # resalta los términos en los resultados
    - search.share             # permite compartir la búsqueda con un link
    - content.code.annotate
    - content.tabs.link 
    - toc.follow

    
    
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
      preserve_tabs: true

plugins:
  - search
  - glightbox:
      touch: true  # Habilita el soporte táctil para dispositivos móviles
      zoom: true  # Habilita el zoom en las imágenes
      autofocus: true # Habilita el foco automático al abrir
      do_not_load: false # Para cargar el plugin en todas las páginas



extra_css:
  - assets/styles/menu-oculto.css
  - https://fonts.googleapis.com/icon?family=Material+Icons

extra_javascript:
  - assets/js/menu.js
